### ISSUE TITLE
gcov ci error

### ISSUE THREAD

**Issue by alfredh** [baresip/re#364]
is there a problem with CI and GCOV ?

```
(WARNING) Unrecognized GCOV output for /home/runner/work/re/re/src/mbuf/mbuf.c
[8](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:8)
	  branch  2 taken -2 (fallthrough)
[9](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:9)
	This is indicative of a gcov output parse error.
[10](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:10)
	Please report this to the gcovr developers
[11](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:11)
	at <https://github.com/gcovr/gcovr/issues>.
[12](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:12)
(WARNING) Exception during parsing:
[13](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:13)
	UnknownLineType: branch  2 taken -2 (fallthrough)
[14](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:14)
(ERROR) Exiting because of parse errors.
[15](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:15)
	You can run gcovr with --gcov-ignore-parse-errors
[16](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:16)
	to continue anyway.
[17](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:17)
Traceback (most recent call last):
[18](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:18)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/workers.py", line 77, in worker
[19](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:19)
    work(*args, **kwargs)
[20](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:20)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov.py", line 317, in process_datafile
[21](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:21)
    done = run_gcov_and_process_files(
[22](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:22)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov.py", line 490, in run_gcov_and_process_files
[23](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:23)
    process_gcov_data(fname, covdata, abs_filename, options)
[24](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:24)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov.py", line 145, in process_gcov_data
[25](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:25)
    coverage = parse_coverage(
[26](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:26)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 370, in parse_coverage
[27](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:27)
    _report_lines_with_errors(lines_with_errors, context)
[28](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:28)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 509, in _report_lines_with_errors
[29](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:29)
    raise errors[0]  # guaranteed to have at least one exception
[30](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:30)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 322, in parse_coverage
[31](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:31)
    tokenized_lines.append((_parse_line(raw_line), raw_line))
[32](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:32)
  File "/home/runner/.local/lib/python3.8/site-packages/gcovr/gcov_parser.py", line 777, in _parse_line
[33](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:33)
    raise UnknownLineType(line)
[34](https://github.com/baresip/re/runs/6439790475?check_suite_focus=true#step:9:34)
gcovr.gcov_parser.UnknownLineType: branch  2 taken -2 (fallthrough)
```

**Comment by alfredh** [comment]
https://github.com/baresip/re/runs/6439790475?check_suite_focus=true

**Comment by sreimers** [comment]
Yes looks like a gcovr bug. Will try to investigate.
